# SPDX-FileCopyrightText: 2026 Tobias Mueller <muelli@cryptobitch.de>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "evolution-jmap-ical-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.evolution-jmap-ical]
path = ".."

# Use independent workspace for fuzzers
[workspace]
members = ["."]

[[bin]]
name = "fuzz_ical_roundtrip"
path = "fuzz_targets/fuzz_ical_roundtrip.rs"
test = false
doc = false
bench = false
