// SPDX-FileCopyrightText: 2026 Tobias Mueller <muelli@cryptobitch.de>
// SPDX-License-Identifier: GPL-3.0-or-later

//! Raw, unsafe FFI bindings to the Evolution Data Server backend libraries
//! (`libebackend-1.2`, `libedata-book-1.2`, `libedata-cal-2.0`) and to Camel
//! (`camel-1.2`), which is where the mail provider lives.
//!
//! Generated by bindgen at build time from the installed EDS headers — see
//! `build.rs` for the allowlist. This crate adds no safety, no lifetimes and
//! no `Drop`; that is [`jmap-backend-core`]'s job. It exists so exactly one
//! place in the tree has to be audited against the C ABI.
//!
//! GLib, GObject and GIO types are re-exported from `glib-sys`, `gobject-sys`
//! and `gio-sys` rather than regenerated, so an `EBookMetaBackend *` is a
//! `GObject *` that the rest of the gtk-rs ecosystem also recognises.
//!
//! Because the bindings are generated from the headers found by pkg-config,
//! this crate is deliberately kept out of the workspace's `default-members`:
//! `cargo test` on a machine without EDS development files must still work.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// bindgen emits `#[doc = ...]`-free opaque structs with no safety docs, and
// unions/pointers it cannot prove are `Send`. Neither is fixable here.
#![allow(clippy::all)]
#![allow(rustdoc::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
