// SPDX-FileCopyrightText: 2026 Tobias Mueller <muelli@cryptobitch.de>
// SPDX-License-Identifier: GPL-3.0-or-later

//! Raw, unsafe FFI bindings to the Evolution Data Server backend libraries
//! (`libebackend-1.2`, `libedata-book-1.2`, `libedata-cal-2.0`) and to Camel
//! (`camel-1.2`), which is where the mail provider lives.
//!
//! Generated by bindgen at build time from the installed EDS headers — see
//! `build.rs` for the allowlist. This crate adds no safety, no lifetimes and
//! no `Drop`; that is [`jmap-backend-core`]'s job. It exists so exactly one
//! place in the tree has to be audited against the C ABI.
//!
//! GLib, GObject and GIO types are re-exported from `glib-sys`, `gobject-sys`
//! and `gio-sys` rather than regenerated, so an `EBookMetaBackend *` is a
//! `GObject *` that the rest of the gtk-rs ecosystem also recognises.
//!
//! Because the bindings are generated from the headers found by pkg-config,
//! this crate is deliberately kept out of the workspace's `default-members`:
//! `cargo test` on a machine without EDS development files must still work.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// bindgen emits `#[doc = ...]`-free opaque structs with no safety docs, and
// unions/pointers it cannot prove are `Send`. Neither is fixable here.
#![allow(clippy::all)]
#![allow(rustdoc::all)]

/// The EDS version pkg-config resolved when `build.rs` chose the include
/// paths these bindings were generated from.
///
/// It is the only one of the three versions in play that is not in the
/// bindings themselves: `EDS_MAJOR_VERSION` and its siblings come from the
/// headers, `eds_major_version` and its siblings from the library loaded at
/// run time, and this one from the `.pc` file that led to both. Naming it
/// separately is what lets `tests/layout.rs` catch a `.pc` file that does not
/// describe the headers beside it, and what lets a failing M10 matrix leg say
/// which EDS it was. See `docs/eds-versions.md`.
pub const EDS_HEADER_VERSION: &str = env!("EDS_HEADER_VERSION");

pub mod compat;

// Suppress unnecessary_transmutes warnings emitted by bindgen for glibc's
// _IO_FILE bitfield accessor in newer container/rustc environments.
#[allow(unnecessary_transmutes)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
pub use generated::*;
