#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Tobias Mueller <muelli@cryptobitch.de>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Renders docs/packaging/copyright (DEP-5) for this project's own source,
# driven by REUSE.toml's [[annotations]] rather than hand-maintained, so a
# license change there cannot silently leave the shipped copyright file
# wrong. Does NOT enumerate third-party Cargo crates statically linked into
# the built .so's (Track C2's harder remaining half): DEP-5's Files field is
# a glob over paths in the source package, and none of those crates' sources
# are vendored here or shipped in the .deb, so there is no path pattern that
# honestly describes them — see docs/NIGHT-LOG.md's 2026-08-19 Track C2 entry.

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

UPSTREAM_CONTACT = "Tobias Mueller <muelli@cryptobitch.de>"
DEFAULT_LICENSE = "GPL-3.0-or-later"
DEFAULT_COPYRIGHT = "2026 Tobias Mueller <muelli@cryptobitch.de>"

LICENSE_TEXT = {
    "GPL-3.0-or-later": """\
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 .
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.
 .
 On Debian systems, the complete text of the GNU General Public
 License version 3 can be found in "/usr/share/common-licenses/GPL-3".""",
    "LGPL-2.1-or-later": """\
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 .
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 Lesser General Public License for more details.
 .
 On Debian systems, the complete text of the GNU Lesser General
 Public License version 2.1 can be found in
 "/usr/share/common-licenses/LGPL-2.1".""",
}


def load_annotations():
    with (REPO_ROOT / "REUSE.toml").open("rb") as f:
        reuse = tomllib.load(f)
    return reuse["annotations"]


def copyright_lines(value):
    return value if isinstance(value, list) else [value]


def files_field(paths):
    # DEP-5's "*" already matches across "/", so REUSE.toml's doubled-star
    # globs collapse onto it losslessly.
    return " ".join(p.replace("**", "*") for p in paths)


def stanza(files, copyright_value, license_id, comment=None):
    lines = [f"Files: {files}"]
    copy_lines = copyright_lines(copyright_value)
    lines.append(f"Copyright: {copy_lines[0]}")
    lines.extend(f" {c}" for c in copy_lines[1:])
    lines.append(f"License: {license_id}")
    if comment:
        lines.append("Comment:")
        lines.extend(f" {line}" for line in comment)
    return "\n".join(lines)


def render(annotations):
    overrides = [a for a in annotations if a.get("precedence") == "override"]
    aggregates = [a for a in annotations if a.get("precedence") == "aggregate"]

    for a in aggregates:
        if (
            a["SPDX-License-Identifier"] != DEFAULT_LICENSE
            or copyright_lines(a["SPDX-FileCopyrightText"]) != [DEFAULT_COPYRIGHT]
        ):
            raise SystemExit(
                "REUSE.toml aggregate annotation no longer matches this "
                "script's DEFAULT_LICENSE/DEFAULT_COPYRIGHT — update both "
                "together, since the default Files: * stanza below is only "
                "correct while they agree: "
                f"{a['path']!r}"
            )

    parts = [
        "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/",
        "Upstream-Name: evolution-jmap",
        f"Upstream-Contact: {UPSTREAM_CONTACT}",
        "Source: https://github.com/muelli/evolution-jmap",
        "",
        stanza(
            "*",
            DEFAULT_COPYRIGHT,
            DEFAULT_LICENSE,
            comment=[
                "Covers this project's own source not named by a more specific",
                "Files stanza below (checked by `reuse lint` against",
                "REUSE.toml and each file's own SPDX header). Generated by",
                "tools/generate-debian-copyright.py from REUSE.toml — do not",
                "hand-edit the Files stanzas; run the script instead.",
                ".",
                "Does not enumerate the license of the ~140 third-party Rust",
                "crates statically linked into the shipped modules (mostly",
                "MIT/Apache-2.0, per rust/Cargo.lock): DEP-5's Files field is",
                "a path glob over the source package, and none of those",
                "crates' sources are vendored here or shipped in this .deb,",
                "so no path pattern would honestly describe them. Left open",
                "for docs/ROADMAP.md Track C2, pending a maintainer call on",
                "representation (a non-Files license-notice appendix vs. full",
                "dh-cargo vendoring under Track C3).",
            ],
        ),
        "",
    ]

    for a in overrides:
        parts.append(
            stanza(
                files_field(a["path"]),
                a["SPDX-FileCopyrightText"],
                a["SPDX-License-Identifier"],
            )
        )
        parts.append("")

    seen_licenses = {DEFAULT_LICENSE} | {a["SPDX-License-Identifier"] for a in overrides}
    for license_id in sorted(seen_licenses):
        text = LICENSE_TEXT.get(license_id)
        if text is None:
            raise SystemExit(f"no License paragraph text on file for {license_id}")
        parts.append(f"License: {license_id}\n{text}")
        parts.append("")

    return "\n".join(parts).rstrip("\n") + "\n"


def main():
    sys.stdout.write(render(load_annotations()))


if __name__ == "__main__":
    main()
