// SPDX-FileCopyrightText: 2026 Tobias Mueller <muelli@cryptobitch.de>
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The same arrangement as eds-sys's build.rs, one library up: generated at
// build time rather than checked in, because Evolution's class structs change
// between releases and a stale committed binding is a silently-wrong ABI
// rather than a build failure. tests/layout.rs cross-checks the result against
// the running GObject type system.

use std::env;
use std::path::PathBuf;

/// Evolution 3.52 is the target, as it is for EDS: the milestone note in the
/// roadmap is that 3.56 replaced GtkUIManager, so a floor lower than this one
/// would be claiming support for releases nothing here has been held against.
const MIN_EVO: &str = "3.52";

/// The classes the setup module subclasses, and their accessors. Everything
/// else in Evolution's headers — the pages, the assistant, the notebook — is
/// reached through the vfuncs of these classes or not at all, so the surface
/// this crate claims to have audited stays a header at a time.
///
/// `ESourceConfigBackend` is the second, and it is the one Evolution's *New
/// Address Book* and *New Calendar* dialogs are built out of:
/// `ESourceConfig` walks every registered subclass of it and makes one
/// candidate — one entry in the Type list, one page of widgets, one
/// commit target — per subclass. Its class struct is generated for the same
/// reason `EMailConfigServiceBackend`'s is, and it is the more load-bearing of
/// the two: four vfunc slots, all four of them written by our `class_init`,
/// and `tests/source_config.rs` pins each one's offset rather than only the
/// struct's total size. `ESourceConfigBackendPrivate` comes with it under the
/// same prefix, as the opaque type the instance's `priv` points at.
///
/// `ESourceConfig` itself does *not*: it is a `GtkBox`, so generating it means
/// generating the GTK class structs [`BLOCKED_GTK_TYPES`] exists to keep out.
/// It joins [`EVO_HANDLES`] instead, on the same argument as the mail config
/// page — nothing here subclasses it, allocates one, or reads a field of it.
///
/// `EConfigLookupWorker` joins it for a different reason: not subclassed, but
/// an *interface* this crate will implement (`jmap-config`'s OAuth 2.0
/// setup-time discovery, following the same pattern
/// `jmap-config/src/oauth2_service.rs` already uses for `EOAuth2Service`), so
/// its vtable's layout matters the same way a subclassed struct's does.
/// `EConfigLookup` itself — the object a worker is registered against and
/// handed back in `run()` — is not: nothing here subclasses it or reads a
/// field of it, so it joins [`EVO_HANDLES`] instead, the same call
/// [`BLOCKED_EVO_TYPES`] already made for `EMailConfigServicePage`.
///
/// `EConfigLookupResult` and `EConfigLookupResultSimple` are the answer a
/// worker's `run()` builds, read against `e-config-lookup-result-simple.c`
/// (gitlab.gnome.org/GNOME/evolution-data-server, `master`) rather than
/// assumed: `e_config_lookup_result_simple_new` is a plain `g_object_new`
/// (transfer full to its caller), every `_add_*` copies the string/value it
/// is given, and nothing here subclasses either type — `run()` only ever
/// calls their constructor and setters — so, like `EConfigLookup`, their
/// class structs are not generated, only their `GType`s and functions
/// (below). `EConfigLookupResultKind` (the enum `_new`'s first argument
/// takes) is generated by the same prefix.
const ALLOWED_TYPES: &[&str] = &[
    "EMailConfigServiceBackend.*",
    "EConfigLookupWorker.*",
    "EConfigLookupResult.*",
    "ESourceConfigBackend.*",
    // The interface jmap-ui's vacation page implements: like
    // `EConfigLookupWorker`'s vtable above, its layout matters the way a
    // subclassed class struct's does, because `interface_init` writes
    // `submit`/`submit_finish` (and the title and sort order) into its
    // fields. The exact name, not a prefix: `EMailConfigPage` itself stays an
    // opaque handle in [`EVO_HANDLES`], and [`BLOCKED_EVO_TYPES`]'s pattern
    // is carved around this one name.
    "EMailConfigPageInterface",
    // The enum `e_cal_source_config_get_source_type` answers with, and the only
    // type generated here that belongs to EDS rather than Evolution: it is
    // libecal's, but a plain C enum rather than an object, and `eds-sys` does
    // not generate it (checked, not assumed — nothing in that crate's surface
    // takes or returns one). A value type has no layout for two copies to
    // disagree about, so generating it here does not repeat the mistake
    // [`BLOCKED_TYPES`] exists to prevent.
    "ECalClientSourceType",
];

/// String macros this crate reads rather than hand-copies: the parameter
/// names `EConfigLookupWorker::run` finds its email address and server list
/// under (`e-config-lookup.h`'s `#define`s), generated as `&CStr` constants
/// by `generate_cstr(true)` below — the same treatment `eds-sys` gives
/// `E_SOURCE_CREDENTIAL_PASSWORD`.
const ALLOWED_VARS: &[&str] = &["E_CONFIG_LOOKUP_PARAM_.*"];

/// The class's own accessors, and the one thing asked of the page it extends.
///
/// The prefix is the *backend*'s, because that is the class this module
/// subclasses and every one of its accessors is a call its vfuncs may
/// legitimately make. The page is not subclassed and not extended by anything
/// here — it is only ever the object a backend hands back — so it is named a
/// function at a time, the way the GTK calls below are: `setup_defaults` needs
/// the address the user typed on the identity page and nothing else, and an
/// `e_mail_config_service_page_.*` would take on the page's scratch sources, its
/// backend lookup and its auto-configuration besides.
const ALLOWED_FUNCTIONS: &[&str] = &[
    "e_mail_config_service_backend_.*",
    "e_mail_config_service_page_get_email_address",
    // The one call `insert_widgets` needs back onto the page rather than the
    // backend: telling the assistant an entry changed, so `check_complete` is
    // asked again. See `EMailConfigPage` below on why the type it takes joins
    // the handles rather than being generated.
    "e_mail_config_page_changed",
    // `EConfigLookupWorker`'s own wrappers — get_type, the display-name
    // dispatch, and the one this crate exists to implement.
    "e_config_lookup_worker_.*",
    // `EConfigLookup`'s own calls `JmapConfigLookup` needs: registering
    // itself in `constructed()`, and handing over a built result in `run()`.
    // Not `_get_source`/`_run`/`_dup_results`/…, which nothing here calls.
    "e_config_lookup_get_type",
    "e_config_lookup_register_worker",
    "e_config_lookup_add_result",
    // `EConfigLookupResultSimple`'s constructor and the setters `run()` uses —
    // a string value for every `[Collection]`/`[Authentication]`/`[Security]`/
    // `[JMAP OAuth2]` field it writes, a boolean for the three `*-enabled`
    // flags, and a uint for the one `servers` entry can name a non-default
    // port on (`[Authentication] port`). Not `_add_int`/`_add_int64`/
    // `_add_uint64`/`_add_double`/`_add_enum`/`_add_value`: this worker's
    // result has no field of those shapes.
    "e_config_lookup_result_simple_new",
    "e_config_lookup_result_simple_add_string",
    "e_config_lookup_result_simple_add_boolean",
    "e_config_lookup_result_simple_add_uint",
    // `ESourceConfigBackend`'s own wrappers, by prefix for the same reason the
    // mail config backend's are: it is a class this crate subclasses, so every
    // one of its accessors is a call our vfuncs may legitimately make.
    "e_source_config_backend_.*",
    // And exactly one call on the `ESourceConfig` those hand back. Not
    // `e_source_config_.*`: that prefix would take on the dialog's page
    // management, its candidate list and its async commit, none of which a
    // backend touches. The rest of what an `insert_widgets` will need off it
    // (`_insert_widget`, `_get_registry`, `_add_refresh_interval`, …) joins
    // this list a line at a time with the code that calls it; `get_type` is
    // here now because `tests/source_config.rs` asks the running type system
    // whether the handle below really is the GtkBox this crate calls it.
    "e_source_config_get_type",
    // The two derived config classes, named a function at a time rather than by
    // prefix — a subclass declares itself an extension of one of these and
    // never calls anything else on it. `e_book_source_config_get_type` and
    // `e_cal_source_config_get_type` are what `class_init` writes into
    // `EExtensionClass::extensible_type`; `_get_source_type` is the one call a
    // vfunc makes, and it is `allow_creation`'s whole content on the calendar
    // side. Deliberately not `e_cal_source_config_add_offline_toggle` or
    // `e_book_source_config_add_autocomplete_check`: no vfunc here builds a
    // widget, and none of Evolution's own cal modules calls the former either.
    "e_book_source_config_get_type",
    "e_cal_source_config_get_type",
    "e_cal_source_config_get_source_type",
    // The notebook, a function at a time like the derived configs above: the
    // GType the vacation extension's `class_init` writes into
    // `extensible_type`, the call that puts its page in, and the two sources
    // the extension gates on (account: backend name) and connects with
    // (collection: `[Authentication]`/`[Security]`). Deliberately not
    // `_get_session`/`_get_identity_source`/`_commit` — nothing here calls
    // them.
    "e_mail_config_notebook_get_type",
    "e_mail_config_notebook_add_page",
    "e_mail_config_notebook_get_account_source",
    "e_mail_config_notebook_get_collection_source",
    // The interface's GType, which is what `InterfaceDecl::filled_by` names
    // when the vacation page registers as an implementer.
    "e_mail_config_page_get_type",
    // The composer, a function at a time, for jmap-ui's scheduled send: the
    // extensible's GType, the editor the UI merge goes through, the header
    // table the From gate reads (its `identity-uid`/`registry` are read as
    // properties, so no further accessors), and the async pair that builds
    // the message the way Send itself would. Deliberately not
    // `e_msg_composer_.*`: that prefix is the whole composer.
    "e_msg_composer_get_type",
    "e_msg_composer_get_editor",
    "e_msg_composer_get_header_table",
    "e_msg_composer_get_message",
    "e_msg_composer_get_message_finish",
    "e_html_editor_get_ui_manager",
    "e_html_editor_get_action_group",
    // The From gate's registry, by evolution-ews's own chain: the table hands
    // out its From header, the header hands out the registry it was built
    // with. (The table itself has no registry accessor or property — checked
    // against e-composer-header-table.c, which keeps an EClientCache.)
    "e_composer_header_table_get_header",
    "e_composer_header_get_registry",
    // Which identity the From line stands at, re-read on every
    // `notify::identity-uid`.
    "e_composer_header_table_dup_identity_uid",
    // The snooze surfaces, a function at a time. The shell view: its GType is
    // the first extensible, its name is the "is this the mail view" gate, and
    // the window is where the 3.52 action/menu layer lives.
    "e_shell_view_get_type",
    "e_shell_view_get_name",
    "e_shell_view_get_shell_window",
    "e_shell_view_get_shell_content",
    "e_shell_window_get_ui_manager",
    "e_shell_window_get_action_group",
    // The registry the snooze gate resolves the folder's account source
    // against; the shell singleton is the one place a shell-view extension
    // can be sure of one.
    "e_shell_get_default",
    "e_shell_get_registry",
    // The detached message window, the second extensible: it merges into a
    // GtkUIManager of its own and *is* its own EMailReader.
    "e_mail_browser_get_type",
    "e_mail_browser_get_ui_manager",
    // The reader face both surfaces hand the snooze action: the selection,
    // the folder it sits in, and (for the browser) the action group.
    "e_mail_reader_get_selected_uids",
    "e_mail_reader_ref_folder",
    "e_mail_reader_get_action_group",
];

/// The GTK calls, named one at a time rather than by prefix.
///
/// This is the whole of what M7's `insert_widgets` needs to build its page: a
/// grid packed into the `GtkBox` Evolution hands it, and in the grid a
/// right-aligned mnemonic label beside a horizontally-expanding entry, per
/// setting. Nothing here is a *convenience*; every name absent from this list is
/// a widget call the module cannot make.
///
/// One at a time and not `gtk_(grid|label|entry)_.*` because a prefix would take
/// on the rest of those classes' APIs — several hundred functions, most of them
/// touching a widget hierarchy that has to be realized, none of them exercised
/// by anything here. A binding surface is a promise that what is in it was
/// looked at, so it grows a line at a time with the code that calls it, and
/// `tests/gtk.rs` names each one back.
///
/// The property *bindings* that give these widgets their values are deliberately
/// not in here: they are `g_object_bind_property` on the `CamelSettings` object,
/// which is `gobject-sys` and already available, so a `GtkEntry`'s `text` needs
/// no GTK entry point of its own.
const ALLOWED_GTK_FUNCTIONS: &[&str] = &[
    // The container Evolution hands `insert_widgets`, and the grid that goes in
    // it.
    "gtk_box_pack_start",
    "gtk_grid_new",
    "gtk_grid_attach",
    "gtk_grid_set_row_spacing",
    "gtk_grid_set_column_spacing",
    // A label per setting: `_with_mnemonic` because the underscore in a
    // translated `_("_Server:")` is the keyboard shortcut, `set_mnemonic_widget`
    // because that shortcut has to land in the entry beside it, and
    // `set_xalign` to right-align it against the entry — the modern spelling of
    // what Evolution's older pages do with the deprecated `gtk_misc_set_alignment`.
    "gtk_label_new_with_mnemonic",
    "gtk_label_set_mnemonic_widget",
    "gtk_label_set_xalign",
    // The entry, and the two calls that make a row of them look like a form.
    "gtk_entry_new",
    "gtk_widget_set_hexpand",
    "gtk_widget_show_all",
    // The security toggle: one check button, bound (like the entries) through
    // a plain property binding rather than a `gtk_toggle_button_.*` call, so
    // this is the only entry point the toggle needs.
    "gtk_check_button_new_with_mnemonic",
    // The status label: a plain (non-mnemonic) label, since `Incomplete`'s
    // text is not the module's own to add a keyboard shortcut to, and the two
    // calls that keep it in step with the account — filled once, then
    // rewritten on every keystroke `on_extension_changed` reacts to, and
    // hidden while there is nothing to say.
    "gtk_label_new",
    "gtk_label_set_text",
    "gtk_widget_set_visible",
    // The authentication-method row: a plain combo, populated with the fixed
    // choices `insert_widgets` offers (`ESourceAuthentication:method`'s
    // `"none"` and this project's own `EOAuth2Service` name) rather than
    // queried from the server, so `_append` is the only mutator this crate
    // needs — no `_remove`/`_insert` a dynamic list would call for.
    "gtk_combo_box_text_new",
    "gtk_combo_box_text_append",
    // The vacation page's own additions. The multi-line body is a text view;
    // its content is read and written through the buffer's `text` *property*
    // (plain `g_object_get`/`_set`, already available from gobject-sys), so
    // no `GtkTextIter` — a caller-allocated sized struct this crate refuses
    // to claim a layout for — ever crosses the boundary.
    "gtk_text_view_new",
    "gtk_text_view_get_buffer",
    // The page itself is a GtkScrolledWindow subclass — EMailConfigPage's
    // prerequisite (G_DEFINE_INTERFACE's third argument upstream; the running
    // 3.52 refuses anything less by exactly that name) — whose one child is a
    // vertical box these two build and add. GTK3 wraps a non-scrollable child
    // in a viewport on its own.
    "gtk_scrolled_window_get_type",
    "gtk_box_new",
    "gtk_container_add",
    // Gating: a control whose server-side feature is absent or not yet known
    // is desensitized, never hidden — stable geometry, and the tooltip can
    // say why.
    "gtk_widget_set_sensitive",
    "gtk_widget_set_tooltip_text",
    // The body should take the page's spare height; everything else keeps
    // its natural size.
    "gtk_widget_set_vexpand",
    // The scheduled-send actions: GtkAction-era (Evolution 3.52's composer
    // still merges through GtkUIManager; 3.56 replaced the whole layer, which
    // is jmap-ui's `menu` seam to port then). Actions are built one by one —
    // `gtk_action_new` + a `g_signal_connect` on `activate` — rather than
    // through `gtk_action_group_add_actions`, whose `GtkActionEntry` array is
    // a struct layout the blocklist keeps out.
    "gtk_action_new",
    "gtk_action_group_add_action",
    "gtk_action_set_sensitive",
    "gtk_ui_manager_add_ui_from_string",
    "gtk_ui_manager_ensure_update",
    // The refusal dialog a failed scheduled send is reported through, and its
    // teardown; also how a scheduled composer window is closed on success.
    "gtk_message_dialog_new",
    "gtk_dialog_run",
    "gtk_widget_destroy",
    // Not called by the module: these are what `tests/gtk.rs` asks the running
    // GTK to confirm the classes above are, since the opaque handles carry no
    // layout to check the way `tests/layout.rs` checks the EDS structs.
    "gtk_widget_get_type",
    "gtk_container_get_type",
    "gtk_box_get_type",
    "gtk_grid_get_type",
    "gtk_label_get_type",
    "gtk_entry_get_type",
    "gtk_check_button_get_type",
    "gtk_combo_box_text_get_type",
    "gtk_text_view_get_type",
    "gtk_text_buffer_get_type",
];

/// Types that already exist, and must not be minted a second time.
///
/// Two lots of them, for the same reason with two different owners. The `G*`
/// spellings are eds-sys's argument verbatim: a regenerated `GObject` has the
/// right layout and the wrong identity, so it is blocked and re-exported from
/// the gtk-rs sys crates. The `E*` and `Camel*` ones are the same argument
/// against *this* crate: `EMailConfigServiceBackend` is an `EExtension` and
/// hands out `ESource`s, `CamelProvider`s and `CamelSettings`, all of which
/// eds-sys already generated from the very same headers. Blocked here and
/// re-exported from there, they stay one type, which is what lets the module's
/// vfuncs be written in terms of the crates that already read and write those
/// objects.
///
/// `ESourceRegistry` and friends match the `ESource` prefix and would be
/// blocked with it; that is correct — eds-sys has them too. The one name that
/// starts `ESource` and is *not* EDS's is `ESourceConfigBackend`, which is why
/// the `ESource` half of this list is built by [`blocked_source_types`] rather
/// than written out here.
const BLOCKED_TYPES: &[&str] = &[
    "G[A-Z].*",
    "_G[A-Z].*",
    "g[a-z]+",
    "va_list",
    "__va_list_tag",
    "_?EExtension[A-Za-z]*",
    "Camel.*",
    "_Camel.*",
    // `EConfigLookupWorker::run`'s own parameters: eds-sys already generates
    // this one (its `e_named_parameters_.*` functions are allowlisted there),
    // so a second copy here would be a type bindgen minted twice rather than
    // the one every EDS-facing crate in this workspace shares.
    "_?ENamedParameters",
];

/// The one `ESource*` name in these headers that eds-sys does not have, and
/// that this crate therefore has to generate rather than borrow: Evolution's
/// own `ESourceConfigBackend`, which lives in `libevolution-util`.
///
/// A prefix, not an exact name: `ESourceConfigBackendClass` and
/// `ESourceConfigBackendPrivate` are exempt with it.
const EXEMPT_FROM_SOURCE_BLOCK: &str = "ESourceConfigBackend";

/// `E(Extension|Source)[A-Za-z]*`'s `ESource` half, minus
/// [`EXEMPT_FROM_SOURCE_BLOCK`].
///
/// The exemption cannot be written as one more allowlist entry, because
/// bindgen's blocklist beats its allowlist: a name in both is referenced by
/// every generated signature and defined by nothing, which is a binding that
/// does not compile (checked, before this function was written). And it cannot
/// be written as a negative lookahead, because bindgen matches a whole type
/// name against `regex`, which has none.
///
/// So it is spelled out the only way an anchored, lookahead-free regex can. For
/// every proper prefix of the exempt name from `ESource` onwards, two
/// alternatives: the prefix exactly, and the prefix followed by any character
/// *other* than the one the exempt name continues with. Their union is every
/// name beginning `ESource` except those beginning with the exempt name — so
/// `ESourceCamel`, `ESourceRegistry` and the rest stay blocked and keep coming
/// from eds-sys, while `ESourceConfigBackend` and its two companions are
/// generated here.
///
/// Note what this deliberately does *not* exempt: `ESourceConfig` itself, and
/// its `Class`/`Private`. They differ from the exempt name at the character
/// after `ESourceConfig`, so the `ESourceConfig` + not-`B` alternative catches
/// them, and they stay blocked — which is what sends them to [`EVO_HANDLES`],
/// where a `GtkBox` subclass belongs.
fn blocked_source_types() -> Vec<String> {
    let exempt = EXEMPT_FROM_SOURCE_BLOCK;
    let mut out = Vec::new();
    for len in "ESource".len()..exempt.len() {
        let prefix = &exempt[..len];
        let next = &exempt[len..len + 1];
        for underscore in ["", "_"] {
            out.push(format!("{underscore}{prefix}"));
            out.push(format!("{underscore}{prefix}[^{next}][A-Za-z]*"));
        }
    }
    out
}

/// GTK's *types*, which this crate does not generate even though it now calls
/// GTK functions.
///
/// There is no gtk-rs `gtk-sys` this crate could re-export them from: GTK 3's
/// sys crate is frozen at the 0.18 generation and depends on `glib-sys` 0.18,
/// while this workspace is on 0.22. Depending on both would put two
/// incompatible `GObject`s in one process — precisely the failure the blocklist
/// above exists to prevent — so the widget calls in [`ALLOWED_GTK_FUNCTIONS`]
/// are generated from these same headers rather than borrowed from a second
/// ecosystem, and the classes they take are declared opaque by
/// [`GTK_HANDLES`] instead of generated.
///
/// Opaque and not generated for two reasons. It keeps `GtkWidgetClass` and the
/// hundred vfunc slots below it out of a binding surface nobody reads; and,
/// more to the point, a generated layout for a GTK class is one nothing here
/// cross-checks — `tests/layout.rs` holds the EDS structs against
/// `g_type_query` because this crate *subclasses* them, whereas no GTK class is
/// subclassed, extended or allocated here. A struct definition would be a claim
/// about a layout for no reason to make one.
const BLOCKED_GTK_TYPES: &[&str] = &["Gtk.*", "_Gtk.*"];

/// Evolution's own classes that this crate reaches only as a pointer, blocked
/// for the same underlying reason the GTK ones are: nothing here subclasses
/// them, so a generated layout would be a claim about a struct nobody reads a
/// field of.
///
/// `EMailConfigServicePage` is a `GtkScrolledWindow` two classes down
/// (`EMailConfigPage` → `EMailConfigActivityPage` → this), so generating it
/// means generating the GTK class structs the blocklist above exists to keep
/// out — bindgen says so plainly, with a `parent: GtkScrolledWindow` field
/// naming a type nothing here defines. It is also a class this crate has no
/// business knowing the shape of: nothing subclasses it, nothing allocates one,
/// and the single call made on it takes it as a pointer.
///
/// So the page joins [`EVO_HANDLES`] instead. The backend class next door is the
/// opposite case and stays generated: it *is* subclassed here, its layout is
/// what `class_init` writes vfunc pointers into, and `tests/layout.rs` holds
/// that layout against `g_type_query`.
const BLOCKED_EVO_TYPES: &[&str] = &[
    // `EMailConfigPage` is spelled exactly (no `[A-Za-z]*` tail) so that
    // `EMailConfigPageInterface` stays generatable — it is the one piece of
    // the page this crate does read fields of, see ALLOWED_TYPES. The
    // activity and service page families stay blocked whole.
    "_?EMailConfigPage",
    "_?EMailConfig(ActivityPage|ServicePage)[A-Za-z]*",
    // The account editor's notebook: reached only as a pointer (get the two
    // sources, add a page), so its GtkNotebook-derived structs stay out for
    // the same reason the service page's do.
    "_?EMailConfigNotebook[A-Za-z]*",
    // The composer and what its accessors hand back: a GtkWindow subclass, a
    // GtkGrid subclass and a GtkGrid subclass again — all reached only as
    // pointers by the scheduled-send extension.
    "_?EMsgComposer[A-Za-z]*",
    "_?EHTMLEditor[A-Za-z]*",
    "_?EComposerHeaderTable[A-Za-z]*",
    // The header class itself, spelled without a tail so that
    // `EComposerHeaderType` — the enum `e_composer_header_table_get_header`
    // takes, a value type — stays generatable.
    "_?EComposerHeader",
    "_?EComposerHeader(Class|Private)",
    // The whole shell family (EShell itself included — a GtkApplication),
    // and the two mail-window classes the snooze extensions reach only as
    // pointers. `EMailReader` is spelled exactly, twice, so that
    // `EMailReaderActionGroup` — the enum `e_mail_reader_get_action_group`
    // takes — stays generatable.
    "_?EShell[A-Za-z]*",
    "_?EMailBrowser[A-Za-z]*",
    "_?EMailReader",
    "_?EMailReaderInterface",
    // `EConfigLookup`: the object an `EConfigLookupWorker` is registered
    // against and handed back as `run()`'s argument. Not `EConfigLookupWorker`
    // or `EConfigLookupResult(Simple)?` — this pattern has no trailing
    // `[A-Za-z]*` so it matches only the exact name, the same way the page
    // above is distinguished from `EMailConfigServiceBackend`.
    "_?EConfigLookup",
    // `EBookSourceConfig` and `ECalSourceConfig`, for the same reason
    // `ESourceConfig` is blocked and handled: each leads with an `ESourceConfig`
    // parent, which is itself a handle here — so a generated struct would put a
    // zero-sized field where a `GtkBox` sits and mislocate everything after it.
    // Neither is subclassed, allocated or read from; the calendar one is only
    // ever the pointer `e_source_config_backend_get_config` handed back, cast
    // the way C's `E_CAL_SOURCE_CONFIG()` casts it.
    "_?E(Book|Cal)SourceConfig[A-Za-z]*",
];

/// Evolution's classes reached only through a pointer, as opaque handles — the
/// same zero-sized `#[repr(C)]` treatment, and the same claim, as [`GTK_HANDLES`].
///
/// The page a service backend extends, and the interface it implements.
///
/// `EMailConfigServicePage` is `tests/page.rs`'s subject: it stays zero-sized,
/// and is the one type both `e_mail_config_service_backend_get_page` and
/// `e_mail_config_service_page_get_email_address` speak of — the whole of what
/// `setup_defaults` does with a page.
///
/// `EMailConfigPage` is the interface `insert_widgets` needs instead:
/// `e_mail_config_page_changed` takes one, not a service page, because the
/// "tell the assistant an entry changed" call is on the interface every config
/// page implements, not on this provider's own subclass. Read against
/// `e-mail-config-service-page.c` (tag 3.52.3) rather than assumed —
/// `E_MAIL_CONFIG_SERVICE_PAGE_TYPE`'s `G_IMPLEMENT_INTERFACE (
/// E_TYPE_MAIL_CONFIG_PAGE, …)` is where that relationship is actually stated —
/// so the page handle `e_mail_config_service_backend_get_page` returns is one
/// `insert_widgets` may cast straight to this handle and hand to the call, the
/// same pointer-is-the-same-object cast `E_MAIL_CONFIG_PAGE()` is in C.
/// `BLOCKED_EVO_TYPES`'s pattern already covers this name, so it joins the
/// handle list rather than being bindgen's own guess at its layout — nothing
/// here subclasses it or reads a field of it either.
///
/// `EConfigLookup` is the third: the object `EConfigLookupWorker::run`
/// receives, used only to call back onto (`e_config_lookup_get_source`,
/// `_add_result`, …) once a worker exists to make those calls — not a widget,
/// but opaque for the identical reason, since nothing here subclasses it or
/// reads a field of it.
///
/// `ESourceConfig` is the fourth, and the closest analogue of the first: it is
/// what `e_source_config_backend_get_config` hands a backend's vfuncs, exactly
/// as the page is what `e_mail_config_service_backend_get_page` hands the mail
/// one, and it is a `GtkBox` — so generating it would pull in the GTK class
/// structs, and would be a claim about a layout nothing here reads a field of.
/// `tests/source_config.rs` asks the running type system for the one thing this
/// treatment does assume, that the handle really is a `GtkBox`, rather than
/// taking the header's word for it. Note the *backend* class beside it is the
/// opposite case and is generated, for the same reason the mail one is.
const EVO_HANDLES: &[&str] = &[
    "EMailConfigServicePage",
    "EMailConfigPage",
    "EConfigLookup",
    "ESourceConfig",
    // The account editor's page container — the extensible jmap-ui's vacation
    // extension names and the object it hands its page to. Nothing here
    // subclasses it or reads a field of it, and it is a GtkNotebook two
    // classes down, which is [`BLOCKED_GTK_TYPES`]'s whole argument.
    "EMailConfigNotebook",
    // Its two derived classes, the fifth and sixth, on exactly the argument the
    // fourth makes: both are `ESourceConfig`s and so `GtkBox`es, and the only
    // thing done with either is to name its `GType` or hand its pointer back to
    // Evolution. `tests/source_config.rs` asks the running type system whether
    // they really do derive from `ESourceConfig`, which is the one thing the
    // `E_CAL_SOURCE_CONFIG()`-shaped cast in `allow_creation` assumes.
    "EBookSourceConfig",
    "ECalSourceConfig",
    // The composer trio the scheduled-send extension reaches only as
    // pointers: the extensible itself, its editor, and the header table whose
    // `identity-uid`/`registry` are read as plain GObject properties.
    "EMsgComposer",
    "EHTMLEditor",
    "EComposerHeaderTable",
    "EComposerHeader",
    // The snooze surfaces: the shell singleton and the mail window's view
    // chain, plus the detached message window and the reader face both share.
    "EShell",
    "EShellView",
    "EShellWindow",
    "EShellContent",
    "EMailBrowser",
    "EMailReader",
];

/// The GTK classes the calls above mention, as opaque handles.
///
/// One `#[repr(C)]` zero-sized struct each, with a private field, so that
/// nothing outside this crate can construct one and nothing inside it can read
/// through one: a pointer to any of these is only ever handed straight back to
/// GTK. `tests/gtk.rs` asserts they all stay zero-sized, which is the
/// machine-checkable form of "this crate does not know what a widget looks
/// like".
///
/// Separate types rather than one alias for `c_void`, which is what `GtkBox`
/// was while there were no calls to make with it. GTK's C API takes the same
/// object as a `GtkGrid *` in one call and a `GtkWidget *` in the next, and with
/// distinct types each of those crossings has to be written as a `.cast()` at
/// the call site — the Rust spelling of C's `GTK_GRID()`. Aliasing them all to
/// `c_void` would instead let a `GtkBox` be passed to `gtk_grid_attach`, which
/// compiles, is undefined behaviour, and is a mistake this file can simply
/// prevent. What licenses the casts that remain is that GTK really does relate
/// the classes this way, which is the one thing `tests/gtk.rs` asks the running
/// type system rather than assuming.
const GTK_HANDLES: &[&str] = &[
    "GtkWidget",
    "GtkBox",
    "GtkGrid",
    "GtkLabel",
    "GtkEntry",
    "GtkComboBoxText",
    "GtkTextView",
    "GtkTextBuffer",
    // What `gtk_container_add` takes; the cast at the call site is the C
    // `GTK_CONTAINER()`.
    "GtkContainer",
    // The GtkAction era's trio, still what 3.52's composer merges through.
    "GtkAction",
    "GtkActionGroup",
    "GtkUIManager",
    // The refusal dialog: constructed as a message dialog, run as a dialog,
    // parented on a window — three names for the same pointer, each cast
    // written down.
    "GtkMessageDialog",
    "GtkDialog",
    "GtkWindow",
];

fn main() {
    println!("cargo:rerun-if-changed=wrapper.h");
    println!("cargo:rerun-if-changed=build.rs");

    let mut clang_args = Vec::new();
    let mut link_paths: Vec<String> = Vec::new();
    for pkg in ["evolution-shell-3.0", "evolution-mail-3.0"] {
        let lib = pkg_config::Config::new()
            .atleast_version(MIN_EVO)
            .probe(pkg)
            .unwrap_or_else(|e| panic!("{pkg} >= {MIN_EVO} not found: {e}"));
        clang_args.extend(
            lib.include_paths
                .iter()
                .map(|p| format!("-I{}", p.display())),
        );
        // Evolution's libraries live in its own private directory
        // (`/usr/lib/evolution`) rather than in the system one, so a binary
        // that links them has to record where they were found or it will not
        // start. Nothing here has to arrange that: both `.pc` files carry a
        // `-Wl,-R<libdir>` in their `Libs:` for exactly this reason, and the
        // `pkg_config` crate forwards it as a link argument — the test binaries
        // come out with the directory in their `RUNPATH`, checked with
        // `readelf -d`.
        //
        // That forwarding stops at this package, though: Cargo scopes
        // `rustc-link-arg` to the crate whose build script emitted it, while
        // the `-l` flags it also emits are passed on to everything that links
        // this crate. A dependent therefore links fine and comes out with no
        // `RUNPATH` at all, which is a binary that cannot start. So the
        // directories are published as build-script metadata — reachable to a
        // dependent as `DEP_EVOLUTION_SHELL_LIBDIRS`, by way of this crate's
        // `links` key — and `jmap-config`'s own `build.rs` turns them back into
        // an rpath for the binaries it produces.
        //
        // Read from `lib.ld_args` (the `-Wl,...` linker options the `.pc`
        // files actually spell out), not `lib.link_paths` (every `-L` search
        // directory pkg-config's recursive `Requires:` resolution turns up,
        // most of it standard system dirs the two `.pc` files never asked to
        // be rpathed at all) — `lib.link_paths` was tried first and made a
        // lintian-clean `.deb` (cmake/tests/check-deb-lintian.cmake) impossible:
        // the installed module came out with `/usr/lib` and
        // `/usr/lib/x86_64-linux-gnu` in its `RUNPATH` alongside the one
        // directory anything here is actually for, and lintian's
        // `custom-library-search-path` flags a RUNPATH entry regardless of
        // whether the directory is also a default one.
        for arg in &lib.ld_args {
            let mut words = arg.iter();
            while let Some(word) = words.next() {
                let dir = if let Some(dir) = word.strip_prefix("-R") {
                    Some(dir)
                } else if let Some(dir) = word.strip_prefix("-rpath=") {
                    Some(dir)
                } else if word == "-rpath" {
                    words.next().map(String::as_str)
                } else {
                    None
                };
                if let Some(dir) = dir.filter(|dir| !dir.is_empty()) {
                    let dir = dir.to_string();
                    if !link_paths.contains(&dir) {
                        link_paths.push(dir);
                    }
                }
            }
        }
    }

    // A colon-separated list, as every other library path in the loader's world
    // is; a directory with a colon in its name would break it, and would break
    // `LD_LIBRARY_PATH` and `-Wl,-rpath` in exactly the same way.
    println!("cargo:libdirs={}", link_paths.join(":"));

    let mut builder = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_args(clang_args)
        .clang_arg("-Wno-deprecated-declarations")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        // Reproducible builds, as in eds-sys.
        .generate_comments(false)
        .layout_tests(false)
        .derive_default(false)
        .prepend_enum_name(false)
        .default_enum_style(bindgen::EnumVariation::Consts)
        .generate_cstr(true)
        .wrap_unsafe_ops(true)
        // One glob, not four: eds-sys re-exports glib-sys, gobject-sys and
        // gio-sys itself, so taking its namespace whole is what makes an
        // `ESource *` here the same Rust type as an `ESource *` in the
        // backends.
        .raw_line("pub use eds_sys::*;");

    // The GTK classes these headers mention, as opaque handles; see GTK_HANDLES.
    for t in GTK_HANDLES {
        builder = builder.raw_line(format!(
            "#[repr(C)]\npub struct {t} {{\n    _opaque: [u8; 0],\n}}"
        ));
    }

    // Two GTK *value* types the surface mentions, supplied rather than
    // generated: `Gtk.*` is blocklisted wholesale, but a plain C enum has no
    // layout for two copies to disagree about (`ECalClientSourceType`'s
    // argument in ALLOWED_TYPES). `GtkAssistantPageType` is a field of the
    // generated `EMailConfigPageInterface` — never written here, the
    // interface's own default stands. `GtkOrientation` is what `gtk_box_new`
    // takes; the one value anything here passes gets its GTK name back.
    builder = builder
        .raw_line("pub type GtkAssistantPageType = ::std::os::raw::c_uint;")
        .raw_line("pub type GtkOrientation = ::std::os::raw::c_uint;")
        .raw_line("pub const GTK_ORIENTATION_VERTICAL: GtkOrientation = 1;")
        // `gtk_message_dialog_new`'s three enum arguments, same argument as
        // the two above; only the values the refusal dialog passes are named.
        .raw_line("pub type GtkDialogFlags = ::std::os::raw::c_uint;")
        .raw_line("pub const GTK_DIALOG_MODAL: GtkDialogFlags = 1;")
        .raw_line("pub const GTK_DIALOG_DESTROY_WITH_PARENT: GtkDialogFlags = 2;")
        .raw_line("pub type GtkMessageType = ::std::os::raw::c_uint;")
        .raw_line("pub const GTK_MESSAGE_ERROR: GtkMessageType = 3;")
        .raw_line("pub type GtkButtonsType = ::std::os::raw::c_uint;")
        .raw_line("pub const GTK_BUTTONS_CLOSE: GtkButtonsType = 2;");

    // And Evolution's, which need the struct tag as well as the typedef: unlike
    // the GTK ones, which bindgen writes into the signatures under their typedef
    // name, a blocklisted `EMailConfigServicePage` comes through as
    // `_EMailConfigServicePage` — the spelling the header's `typedef struct`
    // introduces. So the handle is defined under the tag, which is what the
    // generated declarations refer to, and aliased to the name the headers and
    // the callers use; that is also how bindgen itself writes every Evolution
    // class it does generate.
    for t in EVO_HANDLES {
        builder = builder.raw_line(format!(
            "#[repr(C)]\npub struct _{t} {{\n    _opaque: [u8; 0],\n}}\npub type {t} = _{t};"
        ));
    }

    for t in ALLOWED_TYPES {
        builder = builder.allowlist_type(t);
    }
    for f in ALLOWED_FUNCTIONS.iter().chain(ALLOWED_GTK_FUNCTIONS) {
        builder = builder.allowlist_function(f);
    }
    for v in ALLOWED_VARS {
        builder = builder.allowlist_var(v);
    }
    let source_types = blocked_source_types();
    for t in BLOCKED_TYPES
        .iter()
        .copied()
        .chain(BLOCKED_GTK_TYPES.iter().copied())
        .chain(BLOCKED_EVO_TYPES.iter().copied())
        .chain(source_types.iter().map(String::as_str))
    {
        builder = builder.blocklist_type(t);
    }

    let bindings = builder
        .generate()
        .expect("bindgen failed on the Evolution headers");
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR unset"));
    bindings
        .write_to_file(out.join("bindings.rs"))
        .expect("could not write bindings.rs");
}
